# Description: This file contains the variables that are common to all the hosts in the inventory.
---
params: "{{ project.stages.d1 }}"

workload:
  resources:
    my_rg_1:
      &rg1
      kind: resource_group
      name: "rg1"

    my_storage_1:
      kind: storage_account
      name: "st1"
      resource_group: *rg1